const baseConfig = require('./app.json');

module.exports = baseConfig;
/*module.exports = {
  ...baseConfig,
  extra: {
    FIREBASE_API_KEY: env.EXPO_PUBLIC_FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: env.EXPO_PUBLIC_FIREBASE_APP_ID,
    GEMINI_API_KEY: env.EXPO_PUBLIC_GEMINI_API_KEY,
  },
};*/